version: '2.2'
services:
  garage-ros-intera-py2:
    build:
      context: .
      dockerfile: Dockerfile.ros_intera
      args:
        - PARENT_IMAGE=rlworkgroup/garage-${GARAGE_TYPE}:${GARAGE_VER}
    image: rlworkgroup/garage-${GARAGE_TYPE}-ros-intera-py2:${GARAGE_VER}
  garage-ros-intera:
    build:
      context: .
      dockerfile: Dockerfile.garage_ros_intera
      args:
        - PARENT_IMAGE=rlworkgroup/garage-${GARAGE_TYPE}-ros-intera-py2:${GARAGE_VER}
    image: rlworkgroup/garage-${GARAGE_TYPE}-ros-intera:${GARAGE_VER}
